@extends('layouts.app')
@section('content')
    <search-page
        @if(Auth::check())
            user-id="{{Auth::user()->id}}"
        @endif
        tag="{{$tag}}"
    ></search-page>
@endsection
