@extends('layouts.admin_panel')
@section('content')
    <course-students
        user-id="{{Auth::user()->id}}"
        course-id="{{$course_id}}"
        admin-courses-route="{{route('admin_courses')}}"
        module="{{$course_type}}"
    ></course-students>
@endsection
