@extends('layouts.admin_panel')
@section('content')
    <sub-categories-page
        default-image-path="{{asset('images/courses/course-1.jpg')}}"
        categories-route="{{route('adminCategories')}}"
        selected-category-id="{{$data['categoryId']}}"
        no-content-text="@lang('front/auth.no_content')"
        delete-text="@lang('front/auth.delete')"
        activate-text="@lang('front/auth.activate')"
        deactivate-text="@lang('front/auth.deactivate')"
        edit-text="@lang('front/auth.edit')"
        save-text="@lang('front/auth.save')"
        cancel-text="@lang('front/auth.cancel')"
        add-sub-category-text="@lang('front/auth.add_sub_category')"
        back-text="@lang('front/auth.back')"
        category-text="@lang('front/auth.category')"
        select-category-text="@lang('front/auth.select_category')"
        sub-category-name-text="@lang('front/auth.sub_category_name')"
        sub-category-image-text="@lang('front/auth.sub_category_image')"
        icon-text="@lang('front/auth.icon')"
        select-icon-text="@lang('front/auth.select_icon')"
        select-color-text="@lang('front/auth.select_color')"
        color-text="@lang('front/auth.color')"
        edit-sub-category-text="@lang('front/auth.edit_sub_category')"
        description-text="@lang('front/auth.description')"
        select-file="@lang('front/auth.select_file')"
    ></sub-categories-page>
@endsection
