<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Models\Auth\Instructor;
use App\Models\Auth\User;
use App\Models\Base\School;
use App\Repositories\Auth\InstructorRepository;

class InstructorTest extends TestCase
{
    use WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }

    public function test_all()
    {
        // Data preparation
        factory(Instructor::class, 5)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->all();

        // Control
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
    }

    public function test_get(){
        // Data preparation
        $model = factory(Instructor::class)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->get($model->id);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($model->user_id, $resp->getData()->user_id);
        $this->assertEquals($model->school_id, $resp->getData()->school_id);
        $this->assertEquals($model->identification_number, $resp->getData()->identification_number);
        $this->assertEquals($model->title, $resp->getData()->title);
        $this->assertEquals($model->bio, $resp->getData()->bio);
        $this->assertEquals($model->iban, $resp->getData()->iban);
        $this->assertEquals($model->reference_code, $resp->getData()->reference_code);
    }

    public function test_get_by_reference_code(){
        // Data preparation
        $model = factory(Instructor::class)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->getByReferenceCode($model->reference_code);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($model->id, $resp->getData()->id);
    }

    public function test_create(){
        // Data preparation
        $user = factory(User::class)->create();
        $school = factory(School::class)->create();
        $data = [
            'user_id' => $user->id,
            'identification_number' => $this->faker->bothify('###########'),
            'title' => $this->faker->suffix,
            'bio' => $this->faker->text(500),
            'iban' => $this->faker->iban('TR'),
        ];

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->create($data);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($data['user_id'], $resp->getData()->user_id);
        $this->assertEquals($data['identification_number'], $resp->getData()->identification_number);
        $this->assertEquals($data['title'], $resp->getData()->title);
        $this->assertEquals($data['bio'], $resp->getData()->bio);
        $this->assertEquals($data['iban'], $resp->getData()->iban);
        $this->assertNotNull($resp->getData()->user);
    }

    public function test_update(){
        // Data preparation
        $model = factory(Instructor::class)->create();
        $data = [
            'identification_number' => $this->faker->bothify('###########'),
            'title' => $this->faker->suffix,
            'bio' => $this->faker->text(500),
            'iban' => $this->faker->iban('TR'),
        ];

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->update($model->id, $data);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertFalse($resp->isDataNull());
        $this->assertNull($resp->getError());
        $this->assertEquals($data['identification_number'], $resp->getData()->identification_number);
        $this->assertEquals($data['title'], $resp->getData()->title);
        $this->assertEquals($data['bio'], $resp->getData()->bio);
        $this->assertEquals($data['iban'], $resp->getData()->iban);
    }

    public function test_delete(){
        // Data preparation
        $model = factory(Instructor::class)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->delete($model->id);

        // Controls
        $this->assertNull($resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertTrue($resp->isDataNull());
        $this->assertNull(Instructor::find($model->id));
        $this->assertNotNull(User::find($model->user_id));
        if($model->school_id != null){
            $this->assertNotNull(School::find($model->school_id));
        }
    }

    public function test_set_active(){
        // Data preparation
        $model = factory(Instructor::class)->create(['active' => false]);

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->setActive($model->id);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertTrue($resp->getData()->active);
    }

    public function test_set_passive(){
        // Data preparation
        $model = factory(Instructor::class)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->setPassive($model->id);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertFalse($resp->getData()->active);
    }

    public function test_set_school(){
        // Data preparation
        $model = factory(Instructor::class)->create();
        $school = factory(School::class)->create();

        // Operations
        $repository = new InstructorRepository;
        $resp = $repository->setSchool($model->id, $school->instructor_reference_code);

        // Controls
        $this->assertInstanceOf('App\Models\Auth\Instructor', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($school->id, $resp->getData()->school->id);
    }
}
