<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
use App\Models\Auth\User;
use App\Models\Auth\Student;
use App\Models\Auth\Instructor;
use App\Models\Auth\Manager;
use App\Models\Auth\Admin;
use App\Models\Auth\Guardian;
use App\Models\Base\District;
use App\Repositories\Auth\UserRepository;

class UserTest extends TestCase
{
    use WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
    }

    public function test_all(){
        // Data preparation
        factory(User::class, 5)->create();

        // Operations
        $repository = new UserRepository;
        $resp = $repository->all();

        // Control
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
    }

    public function test_get(){
        // Data preparation
        $district = factory(District::class)->create();
        $data = [
            'district_id' =>  $district->id,
            'first_name' => $this->faker->firstName,
            'last_name' => $this->faker->lastName,
            'username' => $this->faker->userName,
            'email' => $this->faker->email,
            'phone_number' => $this->faker->e164PhoneNumber,
            'password' => '123456',
        ];

        // Operations
        $repository = new UserRepository;
        $userResp = $repository->create($data);
        $model = $userResp->getData();
        $resp = $repository->get($model->id);

        // Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($model->district_id, $resp->getData()->district_id);
        $this->assertEquals($model->first_name, $resp->getData()->first_name);
        $this->assertEquals($model->last_name, $resp->getData()->last_name);
        $this->assertEquals($model->username, $resp->getData()->username);
        $this->assertEquals($model->email, $resp->getData()->email);
        $this->assertEquals($model->phone_number, $resp->getData()->phone_number);
        $this->assertEquals($model->password, $resp->getData()->password);
        $this->assertNotNull($model->student);
    }

    public function test_create(){
        // Data preparation
        $district = factory(District::class)->create();
        $data = [
            'district_id' =>  $district->id,
            'first_name' => $this->faker->firstName,
            'last_name' => $this->faker->lastName,
            'username' => $this->faker->userName,
            'email' => $this->faker->email,
            'phone_number' => $this->faker->e164PhoneNumber,
            'password' => '123456',
        ];

        // Operations
        $repository = new UserRepository;
        $resp = $repository->create($data);

        //Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertFalse($resp->isDataNull());
        $this->assertNull($resp->getError());
        $this->assertEquals($data['district_id'], $resp->getData()->district_id);
        $this->assertEquals($data['first_name'], $resp->getData()->first_name);
        $this->assertEquals($data['last_name'], $resp->getData()->last_name);
        $this->assertEquals($data['username'], $resp->getData()->username);
        $this->assertEquals($data['email'], $resp->getData()->email);
        $this->assertEquals($data['phone_number'], $resp->getData()->phone_number);
        $this->assertNotNull($resp->getData()->student);
    }

    public function test_update(){
        // Data preparation
        $model = factory(User::class)->create();
        $district = factory(District::class)->create();
        $data = [
            'district_id' =>  $district->id,
            'first_name' => $this->faker->firstName,
            'last_name' => $this->faker->lastName,
            'username' => $this->faker->userName,
            'email' => $this->faker->email,
            'phone_number' => $this->faker->e164PhoneNumber,
            'password' => '123456',
        ];

        // Operations
        $repository = new UserRepository;
        $resp = $repository->update($model->id, $data);

        // Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertEquals($data['district_id'], $resp->getData()->district_id);
        $this->assertEquals($data['first_name'], $resp->getData()->first_name);
        $this->assertEquals($data['last_name'], $resp->getData()->last_name);
        $this->assertEquals($data['username'], $resp->getData()->username);
        $this->assertEquals($data['email'], $resp->getData()->email);
        $this->assertEquals($data['phone_number'], $resp->getData()->phone_number);
    }

    public function test_update_avatar(){
        // Data preparation
        $model = factory(User::class)->create();
        $file = UploadedFile::fake()->image('user.jpg');
        $data = [
            'avatar' => $file,
        ];

        // Operations
        $repository = new UserRepository;
        $resp = $repository->updateAvatar($model->id, $data);

        // Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        Storage::assertExists($resp->getData()->avatar);
    }

    public function test_delete(){
        // Data preparation
        $district = factory(District::class)->create();
        $data = [
            'district_id' =>  $district->id,
            'first_name' => $this->faker->firstName,
            'last_name' => $this->faker->lastName,
            'username' => $this->faker->userName,
            'email' => $this->faker->email,
            'phone_number' => $this->faker->e164PhoneNumber,
            'password' => '123456',
        ];

        // Operations
        $repository = new UserRepository;
        $userResp = $repository->create($data);
        $model = $userResp->getData();
        $resp = $repository->delete($model->id);

        // Control
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertTrue($resp->isDataNull());
        $this->assertNull(User::find($model->id));
        $this->assertNull(Student::find($model->student_id));
        if(!is_null($model->admin_id)){
            $this->assertNull(Admin::find($model->admin_id));
        }
        if(!is_null($model->guardian_id)){
            $this->assertNull(Guardian::find($model->guardian_id));
        }
        if(!is_null($model->manager_id)){
            $this->assertNull(Manager::find($model->manager->id));
        }
        if(!is_null($model->instructor_id)){
            $this->assertNull(Instructor::find($model->instructor_id));
        }
    }

    public function test_set_active(){
        // Data preparation
        $model = factory(User::class)->create(['active' => false]);

        // Operations
        $repository = new UserRepository;
        $resp = $repository->setActive($model->id);

        // Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertTrue($resp->getData()->active);
    }

    public function test_set_passive(){
        // Data preparation
        $district = factory(District::class)->create();
        $data = [
            'district_id' =>  $district->id,
            'first_name' => $this->faker->firstName,
            'last_name' => $this->faker->lastName,
            'username' => $this->faker->userName,
            'email' => $this->faker->email,
            'phone_number' => $this->faker->e164PhoneNumber,
            'password' => '123456',
        ];

        // Operations
        $repository = new UserRepository;
        $userResp = $repository->create($data);
        $model = $userResp->getData();
        $resp = $repository->setPassive($model->id);

        // Control
        $this->assertInstanceOf('App\Models\Auth\User', $resp->getData());
        $this->assertTrue($resp->getResult());
        $this->assertNull($resp->getError());
        $this->assertFalse($resp->isDataNull());
        $this->assertFalse($resp->getData()->active);
        $this->assertEquals(0, $model->student->active);
    }
}
